<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$b_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                   ->getStore()
                   ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$_product = $block->getProduct();
$select_brand = $_product->getResource()->getAttribute('select_brand')->getFrontend()->getValue($_product);
if ($select_brand != "No"): ?>
<a href="<?php echo $b_url.'/?select_brand='.$select_brand; ?>">Show All <?php echo $select_brand; ?> Brand Products</a>
<?php endif; 

//echo $product_price; ?>