<?php 
//$attributeCode = 'select_brand';
//$entityType = 'Bag';
// 
//$attributeInfo = $block->getAttributeInfo($entityType, $attributeCode);
//echo $attributeInfo;
//var_dump($attributeInfo->getData());
 
//$attributeId = $attributeInfo->getAttributeId();
//echo $attributeId; // YOUR_OPTION_ID
 
//$attributeOptionAll = $block->getAttributeOptionAll($attributeId);
//var_dump($attributeOptionAll->getData());
 
//$attributeOptionSingle = $block->getAttributeOptionSingle($attributeId, $optionId);
//$_product = $block->getProduct(); echo "<pre>"; print_r($_product->debug());die("dead");


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$b_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
//                  ->getStore()
//                  ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);





$current_category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');




/////

$_product = $block->getProduct();
//$get_cat = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
//       $categoryIds = $get_cat->getCategoryIds();
//       $categoryFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
//
//       $categories = $categoryFactory->create()->addAttributeToSelect('*')->addAttributeToFilter('entity_id', $categoryIds)->setOrder('level', 'DESC'); 
//
//       foreach ($categories as $category){
//           $catname = $category->getUrlKey();
//        }


//////

$brand_name = $_product->getResource()->getAttribute('select_brand')->getFrontend()->getValue($_product);
$brand_id = $_product->getDataByKey('select_brand');
if ($brand_name != "No"): ?>
<style>
.product-info-main .product-reviews-summary, .customer-review .product-reviews-summary
    {
        margin-top: 10px;
    }
</style>
<a href="<?php echo $current_category->getUrl().'?select_brand='.$brand_id; ?>">Show All <?php echo $brand_name; ?> Brand Products</a>
<?php endif; 

//echo $product_price; ?>